### ISSUE TITLE
High memory usage when constructing tree

### ISSUE THREAD

**Issue by earthnuker** [adamreichold/sif-rtree#2]
Hello,

I'm testing different spatial-tree implementations for a project of mine and when testing this one I noticed considerable performance gains compared to what I was using before (~2x speedup), but when constructing the tree the memory usage of my program spikes to around 16GB and then sharply drops again almost immediately

![image](https://github.com/user-attachments/assets/499e38b0-a1a2-484b-9371-b2b0d931ef65)

my point data structure is laid out as follows:
```rust
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct TreeNode {
    /// Internal System ID
    pub id: u32,
    /// Position in space
    pub pos: [f32; 3],
    /// System flags
    #[serde(with = "flags")]
    pub flags: SystemFlags,
}

impl sif_rtree::Object for TreeNode {
    type Point = [f32;3];

    fn aabb(&self) -> (Self::Point, Self::Point) {
        (self.pos,self.pos)
    }
}

impl sif_rtree::Distance<[f32;3]> for TreeNode {
    fn distance_2(&self, point: &[f32;3]) -> f32 {
        self.dist2(point)
    }
}
```
I am constructing the tree with a `node_len` of 512 as I have ~140M nodes that I am loading into the tree

Best regards,

Daniel

**Comment by adamreichold** [comment]
The effect you observed (high memory consumption during construction that settles down immediately afterwards) makes sense: The nodes are constructed accumulated into a `Vec<Node<_>>` which is turned into a `Box<[Node<_>]>` upon completion shedding any excess capacity. Also during construction additional dynamically-sized buffers are required. All of these buffers grow using a doubling capacity approach so they likely have considerable excess capacity. (This appears to match the factor approaching two in your plot.) Always shedding that capacity along the way would really hurt performance in the common case though, so I am not sure what and how much can be done about it.

Your trait implementations certainly look unproblematic. If you have some code and data I could use to reproduce this I could have a look, but I am not optimistic that this can be improved significantly. (The general approach with really large indexes would be to split them into segments where each segment can indexed/built in-memory and then use all segments by memory-mapping them with the kernel handling the necessary paging if the whole of them does not fit into main memory.)

> I am constructing the tree with a node_len of 512 as I have ~140M nodes that I am loading into the tree

If I understand you correctly, you mean that you have a very large `node_len` to reduce the tree-implied memory overhead of the intermediate nodes? I think this would be visible in your steady-state memory consumption. The temporary spike is more likely to be from excess capacity and additional buffers during construction IMO.

Seeing that your data appears to be point-like, you might want to look at the sister crate `sif-kdtree` though. It implements a K-D tree instead which is often a more efficient data structure if the geometry is point-like. It should also not have any memory overhead during construction at all as the data is purely sorted in place.

**Comment by earthnuker** [comment]
Thank you for the very quick and in depth response, during my initial tests I was testing rstar (R*-Tree) and kiddo (KD-Tree) and rstar was (surprisingly) quite a bit more performant than kiddo, which is why my eyes went to the sif-rstar library first. After giving sif-kdtree a shot, it seems like performance is about 4x that of rstar with much faster build times and much more consistent query performance as well as significantly lower memory usage. I think I have a winner for which crate to use in my project.

Best regards,

Daniel
